version: '2'

services:
  vacation-db:
    image: mysql

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= "1127"
      - MYSQL_DATABASE= "td_database"
      - MYSQL_USER= "kangbh98"
      - MYSQL_PASSWORD= "1127"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
      - ./database/datadir/:/var/lib/mysql
    ports:
      - 3306:3306
